# Generated by Django 4.0.6 on 2022-08-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': True},
        ),
    ]
