# Generated by Django 4.0.6 on 2022-08-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'managed': True, 'ordering': ['act_id'], 'verbose_name': 'Tipo de Cuenta', 'verbose_name_plural': 'Tipos de Cuenta'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='account_type',
            field=models.ForeignKey(db_column='account_type', on_delete=django.db.models.deletion.DO_NOTHING, to='Cuentas.tipocuenta'),
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
