# Generated by Django 4.0.6 on 2022-08-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0023_alter_direccion_address_branch_and_more'),
        ('Cuentas', '0003_alter_tipocuenta_options_alter_cuenta_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
    ]
