# Generated by Django 4.0.6 on 2022-08-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0025_alter_direccion_options'),
        ('Cuentas', '0008_alter_movimiento_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='balance',
            field=models.IntegerField(verbose_name='saldo'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='Clientes.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movement_total',
            field=models.IntegerField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movement_type',
            field=models.TextField(choices=[('transf_recib', 'Transferencia Recibida'), ('transf_env', 'Transferencia Enviada'), ('efectivo_ing', 'Ingreso Efectivo'), ('efectivo_eg', 'Egreso Efectivo')], verbose_name='tipo'),
        ),
    ]
