# Generated by Django 4.0.6 on 2022-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0009_alter_cuenta_balance_alter_movimiento_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='movement_type',
            field=models.TextField(choices=[('transf_recib', 'Transferencia Recibida'), ('transf_env', 'Transferencia Enviada'), ('efectivo_ing', 'Ingreso Efectivo'), ('efectivo_eg', 'Egreso Efectivo'), ('prestamo', 'Préstamo Recibido')], verbose_name='tipo'),
        ),
    ]
