# Generated by Django 4.0.6 on 2022-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('account_type', models.ForeignKey('TipoCuenta', models.DO_NOTHING,  db_column='account_type')),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.TextField(blank=True, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Tipos de Cuenta',
                'db_table': 'tipo_cuenta',
                'ordering': ['act_id'],
                'managed': False,
            },
        ),
    ]
