# Generated by Django 4.0.6 on 2022-08-13 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0002_alter_marcatarjeta_options_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcatarjeta',
            options={'managed': True, 'verbose_name': 'Marca Tarjeta'},
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_brand',
            field=models.ForeignKey(db_column='card_brand', on_delete=django.db.models.deletion.DO_NOTHING, to='Tarjetas.marcatarjeta'),
        ),
    ]
