# Generated by Django 4.0.6 on 2022-08-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0023_alter_direccion_address_branch_and_more'),
        ('Tarjetas', '0004_alter_marcatarjeta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tarjetas', to='Clientes.cliente', verbose_name='cliente'),
        ),
    ]
