# Generated by Django 4.0.6 on 2022-08-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0025_alter_direccion_options'),
        ('Tarjetas', '0006_alter_marcatarjeta_options_alter_marcatarjeta_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjeta',
            options={'managed': True, 'ordering': ['card_id'], 'verbose_name': 'Tarjeta', 'verbose_name_plural': 'Tarjetas'},
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='brand',
            field=models.ForeignKey(db_column='card_brand', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tarjetas', to='Tarjetas.marcatarjeta', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_cvv',
            field=models.IntegerField(verbose_name='código valor de validación'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_expiration_date',
            field=models.DateTimeField(verbose_name='fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_from_date',
            field=models.DateTimeField(verbose_name='fecha de expedición'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_number',
            field=models.TextField(unique=True, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_type',
            field=models.TextField(verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='Clientes.cliente', verbose_name='cliente'),
        ),
    ]
