# Generated by Django 4.0.6 on 2022-08-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0007_alter_tarjeta_options_alter_tarjeta_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='card_type',
            field=models.TextField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], verbose_name='tipo'),
        ),
    ]
