# Generated by Django 4.0.6 on 2022-08-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0026_alter_direccion_options'),
        ('Tarjetas', '0013_alter_tarjeta_card_cvv_alter_tarjeta_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='Clientes.cliente', verbose_name='cliente'),
        ),
    ]
