# Generated by Django 4.0.6 on 2022-08-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_brand' , models.ForeignKey('MarcaTarjeta', models.DO_NOTHING, db_column='card_brand')),
                ('card_number', models.TextField(unique=True)),
                ('card_cvv', models.IntegerField()),
                ('card_from_date', models.DateTimeField()),
                ('card_expiration_date', models.DateTimeField()),
                ('card_type', models.TextField()),
                ('card_customer', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
