# Generated by Django 4.0.6 on 2022-08-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0003_alter_marcatarjeta_options_alter_tarjeta_card_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcatarjeta',
            options={'managed': True, 'verbose_name': 'Marca Tarjeta', 'verbose_name_plural': 'Marcas Tarjeta'},
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='card_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='tarjeta',
            old_name='card_customer',
            new_name='customer',
        ),
    ]
