# Generated by Django 4.0.6 on 2022-08-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0005_alter_tarjeta_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcatarjeta',
            options={'managed': True, 'ordering': ['cat_id'], 'verbose_name': 'Marca Tarjeta', 'verbose_name_plural': 'Marcas Tarjeta'},
        ),
        migrations.AlterField(
            model_name='marcatarjeta',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='marcatarjeta',
            name='cat_name',
            field=models.TextField(verbose_name='marca'),
        ),
    ]
