# Generated by Django 4.0.6 on 2022-08-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0009_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='card_expiration_date',
            field=models.DateTimeField(null=True, verbose_name='fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_from_date',
            field=models.DateTimeField(null=True, verbose_name='fecha de expedición'),
        ),
    ]
