# Generated by Django 4.0.6 on 2022-08-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0012_alter_tarjeta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='card_cvv',
            field=models.IntegerField(null=True, verbose_name='código valor de validación'),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='card_number',
            field=models.TextField(null=True, unique=True, verbose_name='número'),
        ),
    ]
