# Generated by Django 4.1 on 2022-08-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.TextField(choices=[('HIPOTECARIO', 'Hipotecario'), ('PRENDARIO', 'Prendario'), ('PERSONAL', 'Personal')]),
        ),
    ]
