# Generated by Django 4.1 on 2022-08-12 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_alter_cliente_user'),
        ('Prestamos', '0003_alter_prestamo_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='Clientes.cliente'),
        ),
    ]
