# Generated by Django 4.1 on 2022-08-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0004_alter_prestamo_customer_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True, 'verbose_name': 'Prestamo'},
        ),
    ]
