# Generated by Django 4.0.6 on 2022-08-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0005_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'managed': True, 'ordering': ['loan_id'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_date',
            field=models.TextField(verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.IntegerField(verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.TextField(choices=[('HIPOTECARIO', 'Hipotecario'), ('PRENDARIO', 'Prendario'), ('PERSONAL', 'Personal')], verbose_name='tipo de Préstamo'),
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='customer_id',
            new_name='customer'
        )
    ]
