# Generated by Django 4.0.6 on 2022-08-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_sucursal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False, 'verbose_name': 'Cliente'},
        ),
    ]
