# Generated by Django 4.0.6 on 2022-08-12 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clientes', '0006_alter_cliente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='branch_id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.sucursal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.tipocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
