# Generated by Django 4.0.6 on 2022-08-12 01:01

from django.db import migrations
import random

def relacion_cliente_user(apps, schema_editor):
    Cliente = apps.get_model('Clientes', 'Cliente')
    User = apps.get_model('auth', 'User')
    for cliente in Cliente.objects.all():
        username = f'{cliente.customer_name}{cliente.customer_surname}{str(cliente.customer_id)}'
        email = f'{username}@gmail.com'
        password = str(random.randint(10000000, 99999999))
        user = User.objects.create_user(username, email, password)
        user.first_name = cliente.customer_name
        user.last_name = cliente.customer_surname
        cliente.user = user
        cliente.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0009_alter_sucursal_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RunPython(relacion_cliente_user),
    ]
