# Generated by Django 4.0.6 on 2022-08-12 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def asignar_nombres_usuarios(apps, schema_editor):
    Cliente = apps.get_model('Clientes', 'Cliente')
    for c in Cliente.objects.all():
        c.user.first_name = c.customer_name
        c.user.last_name = c.customer_surname
        c.user.save()
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Clientes', '0010_rename_user_id_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RunPython(asignar_nombres_usuarios),
    ]
