# Generated by Django 4.0.6 on 2022-08-13 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0012_alter_cliente_client_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True, 'ordering': ['customer_id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False, 'ordering': ['branch_id'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'managed': False, 'ordering': ['clt_id'], 'verbose_name': 'Tipo Cliente', 'verbose_name_plural': 'Tipos de Cliente'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='Clientes.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='Clientes.tipocliente', verbose_name='Tipo cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_dni',
            field=models.TextField(db_column='customer_DNI', verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_name',
            field=models.TextField(verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='customer_surname',
            field=models.TextField(verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dob',
            field=models.TextField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
