# Generated by Django 4.0.6 on 2022-08-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0015_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='a',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='employee_dni',
            field=models.TextField(db_column='employee_DNI', verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='employee_hire_date',
            field=models.TextField(verbose_name='fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='employee_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='employee_name',
            field=models.TextField(verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='employee_surname',
            field=models.TextField(verbose_name='apellido'),
        ),
        migrations.RenameField(
        model_name='empleado',
        old_name='branch_id',
        new_name='branch',
    ),
    ]
