# Generated by Django 4.0.6 on 2022-08-13 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0022_alter_direccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='address_branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direccion', to='Clientes.sucursal', verbose_name='sucursal'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_city',
            field=models.TextField(verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_country',
            field=models.TextField(verbose_name='país'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direcciones', to='Clientes.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='direcciones', to='Clientes.empleado', verbose_name='empleado'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_number',
            field=models.TextField(verbose_name='numero'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_province',
            field=models.TextField(verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='address_street',
            field=models.TextField(verbose_name='calle'),
        ),
    ]
