# Generated by Django 4.0.6 on 2022-08-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0028_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'ordering': ['employee_id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
