# Generated by Django 4.0.6 on 2022-08-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_tipocuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoCuenta',
        ),
    ]
