# Generated by Django 4.0.6 on 2022-08-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_delete_tipocuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True, 'verbose_name': 'Cliente'},
        ),
    ]
