# Generated by Django 4.0.6 on 2022-08-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_alter_tipocliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'managed': False, 'verbose_name': 'Sucursal'},
        ),
    ]
