# Generated by Django 4.1 on 2022-08-12 02:14

from django.db import migrations, models
import django.db.models.deletion
import random

def asignar_tipo_clientes(apps, schema_editor):
    Cliente = apps.get_model('Clientes', 'Cliente')
    TipoCliente = apps.get_model('Clientes', 'TipoCliente')
    for c in Cliente.objects.all():
        tipo = TipoCliente.objects.get(pk = random.randint(1, 3))
        c.client_type = tipo
        c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0011_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.tipocliente', verbose_name='Tipo cliente'),
        ),
        migrations.RunPython(asignar_tipo_clientes),
    ]
