# Generated by Django 4.0.6 on 2022-08-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0016_empleado_a_alter_empleado_employee_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='a',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='branch',
            field=models.IntegerField(),
        ),
    ]
