# Generated by Django 4.0.6 on 2022-08-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0019_remove_empleado_a_alter_empleado_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='Clientes.sucursal', verbose_name='sucursal'),
        ),
    ]
